services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cart-sql
    environment:
      SA_PASSWORD: "BqfTC6!0MDib"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sql:/usr/src/sql


  sql-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: cart-sql-init
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./sql:/usr/src/sql
    entrypoint: >
      /bin/bash -c "
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'BqfTC6!0MDib' -i /usr/src/sql/init.sql
      "
    restart: "on-failure"

  redis:
    image: redis:7
    container_name: cart-redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: cart-api
    depends_on:
      sql-init:
        condition: service_completed_successfully
      redis:
        condition: service_started
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=EcommerceDb;User Id=sa;Password=BqfTC6!0MDib;"
      ConnectionStrings__Redis: "redis:6379"
    ports:
      - "5055:5055"
